export const API_ENDPOINTS = {
  SITES: {
    LIST: '/api/sites',
    STATUS: (domain: string) => `/api/site/${domain}/status`,
    FILES: (domain: string) => `/api/site/${domain}/files`,
    FILES_READ: (domain: string) => `/api/site/${domain}/files/read`,
    FILES_WRITE: (domain: string) => `/api/site/${domain}/files/write`,
    FILES_DELETE: (domain: string) => `/api/site/${domain}/files/delete`,
    FILES_UPLOAD: (domain: string) => `/api/site/${domain}/files/upload`,
    FILES_DOWNLOAD: (domain: string) => `/api/site/${domain}/files/download`,
    DATABASE: (domain: string) => `/api/site/${domain}/database/info`,
    DATABASE_TABLES: (domain: string) => `/api/site/${domain}/database/tables`,
    DATABASE_TABLE_DATA: (domain: string, table: string) => `/api/site/${domain}/database/table/${table}`,
    DATABASE_QUERY: (domain: string) => `/api/site/${domain}/database/query`,
    DATABASE_BACKUP: (domain: string) => `/api/site/${domain}/database/backup`,
    DATABASE_BACKUPS: (domain: string) => `/api/site/${domain}/database/backups`,
    DATABASE_RESTORE: (domain: string) => `/api/site/${domain}/database/restore`,
    FILE_BACKUPS: (domain: string) => `/api/site/${domain}/files/backups`,
    FILE_BACKUP: (domain: string) => `/api/site/${domain}/files/backup`,
    FILE_RESTORE: (domain: string) => `/api/site/${domain}/files/restore`,
    BACKUP_SETTINGS: (domain: string) => `/api/site/${domain}/backups/settings`,
    ACTIVE_BACKUPS: (domain: string) => `/api/site/${domain}/backups/active`,
    WORDPRESS: (domain: string) => `/api/site/${domain}/wordpress/info`,
    WORDPRESS_INFO: (domain: string) => `/api/site/${domain}/wordpress/info`,
    WORDPRESS_CHANGE_DOMAIN: (domain: string) => `/api/site/${domain}/wordpress/change-domain`,
    WORDPRESS_CHECK_DNS: (domain: string) => `/api/site/${domain}/wordpress/check-dns`,
    WORDPRESS_PLUGINS: (domain: string) => `/api/site/${domain}/wordpress/plugins`,
    WORDPRESS_PLUGIN_ACTION: (domain: string, plugin: string, action: string) => `/api/site/${domain}/wordpress/plugins/${plugin}/${action}`,
    WORDPRESS_THEMES: (domain: string) => `/api/site/${domain}/wordpress/themes`,
    WORDPRESS_THEME_ACTIVATE: (domain: string, theme: string) => `/api/site/${domain}/wordpress/themes/${theme}/activate`,
    WORDPRESS_THEME_ENABLE: (domain: string, theme: string) => `/api/site/${domain}/wordpress/themes/${theme}/enable`,
    WORDPRESS_THEME_DISABLE: (domain: string, theme: string) => `/api/site/${domain}/wordpress/themes/${theme}/disable`,
    LOGS: (domain: string, type: string) => `/api/site/${domain}/logs/${type}`,
  },
  SERVICES: {
    LIST: '/api/services',
    CONTROL: (service: string, action: string) => `/api/service/${service}/${action}`,
    LOGS: (service: string) => `/api/service/${service}/logs`,
  },
  SYSTEM: {
    RESOURCES: '/api/system/resources',
    INFO: '/api/system/info',
  },
  CRON: {
    LIST: '/api/cron/list',
    CREATE: '/api/cron/create',
    DELETE: '/api/cron/delete',
    TOGGLE: '/api/cron/toggle',
  },
  CLOUDFLARE: {
    CONFIG: '/api/cloudflare/config',
    ZONES: '/api/cloudflare/zones',
    CREATE_ZONE: '/api/cloudflare/zones/create',
    DNS_RECORDS: (zoneId: string) => `/api/cloudflare/zones/${zoneId}/dns`,
    DNS_RECORD: (zoneId: string, recordId: string) => `/api/cloudflare/zones/${zoneId}/dns/${recordId}`,
    EMAIL_ROUTING: (zoneId: string) => `/api/cloudflare/zones/${zoneId}/email/routing`,
    EMAIL_ADDRESSES: (zoneId: string) => `/api/cloudflare/zones/${zoneId}/email/addresses`,
    EMAIL_ADDRESS: (zoneId: string, tag: string) => `/api/cloudflare/zones/${zoneId}/email/addresses/${tag}`,
  },
  EMAIL: {
    CONFIG: '/api/email/config',
    SEND: '/api/email/send',
    USERS: '/api/email/users',
  },
} as const;